export const environment = {
// url:"https://unidappback.azurewebsites.net",
//   autenticacion:"/authenticate",
//   usuarios:'/findAllUsers',
//   establecimientos: '/getMyEstablishments',
//   options: '/getMyOptions',
//   production: true,
//   establecimiento: '/establishment',
//   update: '/saveEstablishment',
//   user: '/user',
//   saveUser: '/saveUser',
//   vecino: '/neighbor',
//   vecinoPorEstablecimiento: '/getByEstablishment',
//   neighbor: '/neighbor',
//   saveNeighbor: '/saveNeighbor',
//   asset: '/asset',
//   saveAsset: '/saveAsset',
//   getByNum_interno: '/getByNum_interno',
//   billboard: '/billBoard',
//   newsletter: '/newsletter',
//   saveNewsletter: '/saveNewsletter',
//   getByEstablishment: '/getByEstablishment',
//   delete: '/delete',
//   unassociateAsset: '/unassociateAsset',
//   permission: '/permission',
//   getPermissionsByOption: '/getPermissionsByOption',
//   getRole: '/getRole',
//   restorePassword: '/restorePassword',
//   changePassword: '/changePassword',
//   getNews: '/news',
//   getByAssetEstablishment: '/getByAssetEstablishment',
//   firebaseConfig: {
//       apiKey: "AIzaSyAh-UnJ1nF5Pd2E4ly4X8vwA7nQGz3CNKY",
//       authDomain: "unidapp-385a8.firebaseapp.com",
//       databaseURL: "https://unidapp-385a8.firebaseio.com",
//       projectId: "unidapp-385a8",
//       storageBucket: "unidapp-385a8.appspot.com",
//       messagingSenderId: "997451424192",
//       appId: "1:997451424192:web:ff1d865364f67a1f536825",
//       measurementId: "G-QTY9N0Q2E7"
//     },
//     urlNotificationPost: 'https://fcm.googleapis.com/fcm/send',
//     keyNotification: 'key=AAAA6Dy84cA:APA91bFnqif5ZdfVlW60wV3ltfrvqjDtbCRp3ht-1saoE77RMjv05dJ-nTQB5mgohuzsjYk04dMyMpKCpLRFIj-lG0J1LZXSu-zhU1CNrF73UIyxRWFFfXgla4Eqbzh3SxynvLRwq8uD',
//     category:"/category",
//   saveCategory: "/saveCategory",
//   pqrs: "/pqrs",
//   imgDefault: "https://firebasestorage.googleapis.com/v0/b/paco-prod.appspot.com/o/default%2FimgDefault.png?alt=media&token=421ebf2b-cdb1-4786-b61a-e386a28618e3",
//   savePqrs : "",
//   getAll : "",
//   getByAsset: "",
//   getByCategory: "",
//   getByNeighbor: ""


    //url:"https://pacoprod-back.azurewebsites.net",
    url:"http://192.168.100.99:8080",
    autenticacion:"/authenticate",
    usuarios:'/findAllUsers',
    establecimientos: '/getMyEstablishments',
    options: '/getMyOptions',
    production: true,
    establecimiento: '/establishment',
    update: '/saveEstablishment',
    user: '/user',
    saveUser: '/saveUser',
    vecino: '/neighbor',
    vecinoPorEstablecimiento: '/getByEstablishment',
    neighbor: '/neighbor',
    saveNeighbor: '/saveNeighbor',
    asset: '/asset',
    saveAsset: '/saveAsset',
    getByNum_interno: '/getByNum_interno',
    billboard: '/billBoard',
    newsletter: '/newsletter',
    saveNewsletter: '/saveNewsletter',
    getByEstablishment: '/getByEstablishment',
    delete: '/delete',
    unassociateAsset: '/unassociateAsset',
    permission: '/permission',
    getPermissionsByOption: '/getPermissionsByOption',
    getRole: '/getRole',
    restorePassword: '/restorePassword',
    changePassword: '/changePassword',
    getNews: '/news',
    getByAssetEstablishment: '/getByAssetEstablishment',
    firebaseConfig: {
      apiKey: "AIzaSyD0DGbZLnwN2x1U5KXyXbxAE1Y-nF8m0yI",
      authDomain: "unidapp-paco.firebaseapp.com",
      databaseURL: "https://unidapp-paco-default-rtdb.firebaseio.com",
      projectId: "unidapp-paco",
      storageBucket: "unidapp-paco.appspot.com",
      messagingSenderId: "38590311552",
      appId: "1:38590311552:web:735c9375111abb8bc94a65"
    },
    urlNotificationPost: 'https://fcm.googleapis.com/fcm/send',
    keyNotification: 'key=AAAACPwpbIA:APA91bES6WVnyJeIUh6VQcJJ7WlSHOT577MM09g9rwGC3CiSFIUTYrbh4jzK5MJWFEnq4ijoKJjTOvp5gMEmtiz9XkORGfoHIXNC802js1ycoENyb8Q9RmODCij4eVbropyUZ_VCT0q6',
    category:"/category",
    saveCategory: "/saveCategory",
  pqrs: "/pqrs",
  //imgDefault: "https://firebasestorage.googleapis.com/v0/b/paco-prod.appspot.com/o/default%2FimgDefault.png?alt=media&token=421ebf2b-cdb1-4786-b61a-e386a28618e3",
  savePqrs : "",
  getAll : "",
  getByAsset: "",
  getByCategory: "",
  getByNeighbor: ""
};
